export enum ICON_TYPE {
  LOGOUT = 'LOGOUT',
  INVOICES = 'INVOICES',
  KEY = 'KEY',
  SKIPPED_LEADS = 'SKIPPED_LEADS',
  LEADS = 'LEADS',
  AVAILABLE_LEADS = 'AVAILABLE_LEADS',
  EYE_ON = 'EYE_ON',
  EYE_OFF = 'EYE_OFF',
}
